Fix docutils ImportError on the multinode job
For some reasons, the multinode job is failing with an import error
on the subnode:

    ImportError: No module named docutils

Maybe it's due to a missing dependency somewhere.
(I haven't investigated yet.)
This commit workarounds the issue by having docutils
in test-requirements.txt for now.

Closes-Bug: #1759454
Change-Id: I0b04c7eace84d1f40cdf00cb06355038b9fc6b5e